<a href="https://colab.research.google.com/github/Raidin/HowDoDeepLearning/blob/remind_basic_skill/Numpy_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
import numpy as np

def ResultPrint(arr):
    print(arr)
    print(arr.shape)

'''
Initialize
'''
# List를 사용한 방법
# 1D
tmp_arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = np.array(tmp_arr)
ResultPrint(arr)

tmp_arr = [[0,1,2,3,4],[5,6,7,8,9]]
arr = np.array(tmp_arr)
ResultPrint(arr)

# Numpy에서 제공하는 함수
# zeros() : 0 으로 초기화된 array
arr = np.zeros(10)
ResultPrint(arr)

arr = np.zeros((2, 5))
ResultPrint(arr)

# ones() : 1 으로 초기화된 array
arr = np.ones(10)
ResultPrint(arr)

arr = np.ones((2, 5))
ResultPrint(arr)

# full() : 사용자가 지정한 값으로 초기화된 array
val = 5
arr = np.full(10, val)
ResultPrint(arr)

arr = np.full((2,5), val)
ResultPrint(arr)

# eye() : 단위행렬 생성
arr = np.eye(5)
ResultPrint(arr)

# reshpe() : 행렬의 차원수를 변경
arr = np.ones(10)
arr = arr.reshape(2,5)
ResultPrint(arr)

'''
Arithmetic Operation
'''
arr_a = np.array([1, 2, 3, 4, 5, 6])
arr_b = np.array([6, 5, 4, 3, 2, 1])

# Addtion
add = arr_a + arr_b
add_method = np.add(arr_a, arr_b)
print(add, add_method)

# Subtract
sub = arr_a - arr_b
sub_method = np.subtract(arr_a, arr_b)
print(sub, sub_method)

# Multiply
mul = arr_a * arr_b
mul_method = np.multiply(arr_a, arr_b)
print(mul, mul_method)

# Divide
div = arr_a / arr_b
div_method = np.divide(arr_a, arr_b)
print(div, div_method)

# Matrix Product
arr_a = np.array(range(0,6,1)).reshape(3,2)
arr_b = np.array(range(2,8,1)).reshape(3,2)
dot = np.dot(arr_a, arr_b.T) # 3 x 2 dot 2 x 3
print(dot)

# Search Min/Max Value
max_val = np.max(arr_a)
min_val = np.min(arr_a)
print(max_val, min_val)


[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(2, 5)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(10,)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)
[5 5 5 5 5 5 5 5 5 5]
(10,)
[[5 5 5 5 5]
 [5 5 5 5 5]]
(2, 5)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)
[7 7 7 7 7 7] [7 7 7 7 7 7]
[-5 -3 -1  1  3  5] [-5 -3 -1  1  3  5]
[ 6 10 12 12 10  6] [ 6 10 12 12 10  6]
[0.16666667 0.4        0.75       1.33333333 2.5        6.        ] [0.16666667 0.4        0.75       1.33333333 2.5        6.        ]
[[ 3  5  7]
 [13 23 33]
 [23 41 59]]
5 0
