<a href="https://colab.research.google.com/github/Raidin/HowDoDeepLearning/blob/remind_basic_skill/Numpy_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
'''
Initialize
'''
# List를 사용한 방법
# 1D
tmp_arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = np.array(tmp_arr)
print(arr)

tmp_arr = [[0,1,2,3,4],[5,6,7,8,9]]
arr = np.array(tmp_arr)
print(arr)

# Numpy에서 제공하는 함수
# zeros() : 0 으로 초기화된 array
arr = np.zeros(10)
print(arr)

arr = np.zeros((2, 5))
print(arr)

arr= np.zeros_like(tmp_arr, dtype=int)
print(arr)

# ones() : 1 으로 초기화된 array
arr = np.ones(10)
print(arr)

arr = np.ones((2, 5))
print(arr)

# full() : 사용자가 지정한 값으로 초기화된 array
val = 5
arr = np.full(10, val)
print(arr)

arr = np.full((2,5), val)
print(arr)

arr = np.empty_like(tmp_arr, dtype=int)
print(arr)

# eye() : 단위행렬 생성
arr = np.eye(5)
print(arr)

arr = np.eye(5, 5, k=1, dtype=int)
print(arr)

arr = np.identity(5)
print(arr)

# arange()
arr = np.arange(0, 10, 5)
print(arr)

arr = np.arange(1, 10, 5)
print(arr)

arr = np.arange(0, 10, 1)
print(arr)

# linspace() --> linear
arr = np.linspace(0, 10, 5, True, True)
print(arr)

arr = np.linspace(1, 10, 5, True, False)
print(arr)

arr = np.linspace(0, 10, 5, False, False)
print(arr)

# logspace()
arr = np.logspace(0, 10, 5, True, 10.0)
print(arr)

arr = np.logspace(1, 10, 5, True, 5.0)
print(arr)

arr = np.logspace(0, 10, 5, False, 1.0)
print(arr)

# reshpe() : 행렬의 차원수를 변경
arr = np.ones(10)
arr = arr.reshape(2,5)
print(arr)


In [0]:
'''
Arithmetic Operation
'''
arr_a = np.array([1, 2, 3, 4, 5, 6])
arr_b = np.array([6, 5, 4, 3, 2, 1])

# Addtion
add = arr_a + arr_b
add_method = np.add(arr_a, arr_b)
print(add, add_method)

# Subtract
sub = arr_a - arr_b
sub_method = np.subtract(arr_a, arr_b)
print(sub, sub_method)

# Multiply
mul = arr_a * arr_b
mul_method = np.multiply(arr_a, arr_b)
print(mul, mul_method)

# Divide
div = arr_a / arr_b
div_method = np.divide(arr_a, arr_b)
print(div, div_method)

# Matrix Product
arr_a = np.array(range(0,6,1)).reshape(3,2)
arr_b = np.array(range(2,8,1)).reshape(3,2)
dot = np.dot(arr_a, arr_b.T) # 3 x 2 dot 2 x 3
print(dot)

# Search Min/Max Value
max_val = np.max(arr_a)
min_val = np.min(arr_a)
print(max_val, min_val)

In [50]:
'''
Randomize
'''
np.random.seed(7777)

# 배열에서 n개의 무작의 값을 선택해서 반환
arr = np.arange(0,10)
arr = np.random.choice(arr, 5, replace=False, p=[0, 0, 0.05, 0, 0.05, 0, 0.05, 0.05, 0.8, 0]) # replace : 중복반환 여부, p = 배열 각 인덱스별 선택될 확률
print(arr)

# 난수 발생
arr = np.random.rand(3, 3)
print(arr)
arr = np.random.randn(3, 3) # Normal distribution
print(arr)
arr = np.random.randint(1, 10, (3, 3), dtype='int') # 1~10사이의 숫자를 무작위로 선택하여 3x3 배열 반환
print(arr)
arr = np.random.uniform(1, 10, (3, 3)) # 1~10 사이에서 균일한 분포의 3x3 배열 반환
print(arr)
arr = np.random.lognormal(1, 10, (3, 3)) # 1~10 사이에서 평균, 시그마를 대입한 로그정규분포의 3x3 배열 반환
print(arr)
arr = np.random.laplace(1, 10, (3, 3)) # 1~10 사이에서 에타와 나무다를 대입한 라플라스 분포의 무작위 배열
print(arr)


[8 4 6 2 7]
[[0.88514856 0.26354891 0.96610934]
 [0.6176792  0.15060253 0.25199137]
 [0.28181813 0.8640667  0.36500379]]
[[-1.23788204 -0.35068395 -0.28137599]
 [-0.88049182  1.55142052 -0.22116517]
 [ 0.26783721  0.8837513  -1.26581654]]
[[3 2 8]
 [4 1 9]
 [5 5 7]]
[[7.67689373 8.09814389 6.27669686]
 [2.13993826 5.11503081 3.56684078]
 [5.56532423 4.59895113 2.97172784]]
[[2.05001260e+00 5.44922864e-06 2.12300072e+02]
 [9.85570860e+04 5.03911329e-02 1.07358789e+11]
 [3.11022270e+02 1.37812558e+04 1.29506425e+06]]
[[-18.07828065  19.89507972  -1.86022834]
 [ 24.43076488 -22.96287873  -9.44134798]
 [-13.85351943   5.47381061   1.69743012]]


In [63]:
'''
Merge
'''
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6], [7, 8]])

[[[1, 2],[5, 6]],[[3, 4],[7, 8]]]

# horizontal(x) 방향으로 배열을 이어 붙임
arr = np.hstack([arr_a, arr_b]) 
print(arr)
# vertical(y) 방향으로 배열을 이어 붙임
arr = np.vstack([arr_a, arr_b])
print(arr)

arr = np.stack([arr_a, arr_b], axis=0) # axis : x
print(arr)
arr = np.stack([arr_a, arr_b], axis=1) # axis : y
print(arr) 
arr = np.stack([arr_a, arr_b], axis=2) # axis : diagonal
arr = np.dstack([arr_a, arr_b])
print(arr)

arr = np.tile(arr_a, 2)
print(arr)


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
[[1 2 1 2]
 [3 4 3 4]]
